apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Values.namespace.name }}
    name: techtrends
    labels:
        app: techtrends
spec:
    ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      {{- if eq .Values.service.targetPort "" }}
      targetPort: {{ .Values.service.port }}
      {{- else }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end}}
    selector:
        app: techtrends
    type: {{ .Values.service.type }}

