apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Values.namespace.name }}
    name: techtrends
    labels:
        app: techtrends
spec:
    ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targePort }}
    selector:
        app: techtrends
    type: {{ .Values.service.type }}

