apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
	name: techtrends-staging
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/bhatsubhas/nd064_course_1
        path: project/helm
        targetRevision: HEAD
        helm:
            valueFiles:
                - values-staging.yaml
     destination:
        namespace: default
        server: https://kubernetes.default.svc

