name: TechTrends - Package with Docker

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bhatsubhas/techtrends
          flavor: latest=auto
          tags: |
            type=ref, event=branch
            type=semver, pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push TechTrends Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: project/techtrends
          file: project/techtrends/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
