namespace:
    name: sandbox

replicaCount: 1

image:
    repository: techtrends
    tag: latest
    pullPolicy: IfNotPresent

containerPort: 3111

resources:
    requests:
        memory: 64Mi
        cpu: 250m
    limits:
        memory: 128Mi
        cpu: 500m

service:
    protocol: TCP
    type: ClusterIP
    port: 4111
    targetPort: 3111
